[phases.setup]
nixPkgs = ["dotnet-sdk_8"]

[phases.install]
cmds = ["dotnet restore BiketaBai.csproj"]

[phases.build]
cmds = ["dotnet publish BiketaBai.csproj -c Release -o out --no-restore"]

[start]
cmd = "dotnet out/BiketaBai.dll"

